### ISSUE TITLE
Frontported :D

### ISSUE THREAD

**Issue by Inn3rstellar** [Schubilegend/SchubiRat#12]
Let's just say I frontported this into fabric 1.20.1. anyway, how do i reemove connect to localhost. its crashing
![image](https://github.com/Schubilegend/SchubiRat/assets/145948032/b16db2d0-8bae-4655-9b60-2b4798b0ccdb)

**Comment by Majanito** [comment]
There is no connection to localhost in the original code

**Comment by Inn3rstellar** [comment]
oh
