### ISSUE TITLE
which URL Should i paste 

### ISSUE THREAD

**Issue by TheVooDooGuy** [Schubilegend/SchubiRat#19]
You said "Change the URL / IP of the mod to yours using a java string editor or Recaf (Look for "YOUR URL HERE")"
idk what should i paste "YOUR URL HERE" with like should i paste the IP in the console or the API link 

if the IP in the console there's some problem for some reason when i start render it run the command "python main.py" 2 time so i have 2 IP's and when i use any of them i get a status code 404 or 401 and if the API when i use the API i also get the same 2 errors and sometimes  no error 

i need to know which URL/IP do i have to copy.

thx

**Comment by TheVooDooGuy** [comment]
@Majanito

**Comment by Majanito** [comment]
Depends on what you are using. 
If you use render to host your site you put the link they give you, so "https://[THE_NAME_RENDER_GIVES_YOU].onrender.com"
If you are hosting it on a VPS, you either put "http://[YOUR_IP]" if you don't have a domain, or "http[s]://YOUR_DOMAIN.TLD" if you do have a domain.

**Comment by TheVooDooGuy** [comment]
Thanks!
