### ISSUE TITLE
Discord being pulled twice

### ISSUE THREAD

**Issue by ghost** [Schubilegend/SchubiRat#5]
When run, after all is complete the discord embed has been sent twice, any fixes?

Edit: also just want to say i love what you are doing and this has really helped me learn java, thanks so much <3

**Comment by Majanito** [comment]
The Discord embed might be sent twice because you are logged into the same Discord account more than once, for example, in your Discord client and in your browser.

**Comment by ghost** [comment]
Yep thanks!

Also thanks for your message through the webhook haha, scared me :)
