### ISSUE TITLE
Compiling the mod

### ISSUE THREAD

**Issue by JoshFid** [Schubilegend/SchubiRat#6]
Sorry if this is a dumb question but I've followed all of the instructions up until step 4 on Mod/Client. I'm not sure what it means to "compile" the mod and how I would go about doing that. other than that its a very easy process! (please help me lol)

**Comment by 7580jksd-035jsad-925bjnf** [comment]
compiling the mod means taking all the java that is written and smushing it into a .jar file for running through forge, to do this you need jdk17 in your home variable and jdk8 in your project in your project settings, then compile the mod through your ide or the gradlew file or gradlew.bat for windows
