### ISSUE TITLE
Webhook status code 400: {"embeds": ["Embed size exceeds maximum size of 6000"]}

### ISSUE THREAD

**Issue by Audjfi1qw1232** [Schubilegend/SchubiRat#9]
I'm getting the error above which is probably related to the Discord Webhook in the console,
![zadsdas12](https://github.com/Schubilegend/SchubiRat/assets/33324160/ef63b74c-7940-4d6e-82ec-16d8c73f7f9b)

And this is the error once the mod launches:

![image](https://github.com/Schubilegend/SchubiRat/assets/33324160/99727fb1-6617-4f89-95e3-5c078cff5916)

**Comment by NotAiTristanAlt** [comment]
It means the file size exceeds maximum discord upload size, only way to fix is to boost your server or rewrite code to use something other than discord.

**Comment by schubilegend** [comment]
We will fix this soon

**Comment by Majanito** [comment]
Should be fixed now
